name: new-benchmark-fp
channels:
  - pyg
  - nvidia
  - defaults
  - dglteam
  - pytorch
  - conda-forge
dependencies:
  - ca-certificates=2023.12.12
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - ase==3.22.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - drfp==0.3.6
      - fonttools==4.49.0
      - future==1.0.0
      - hyperopt==0.2.7
      - importlib-resources==6.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.3
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==23.2
      - periodictable==1.6.1
      - pandas==2.2.1
      - pillow==10.2.0
      - py4j==0.10.9.7
      - pyparsing==3.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - qml==0.4.0.27
      - rdkit==2023.3.3
      - rdkit-pypi==2022.9.5
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - six==1.16.0
      - threadpoolctl==3.3.0
      - tqdm==4.66.2
      - tzdata==2024.1
      - zipp==3.17.0
